version: '3.8'

services:
  agent:
    image: inventory-osquery
    build: ./docker/osquery
    command: ["--flagfile", "/etc/osquery.flags"]
    volumes:
      - ./staks/osquery/osquery.flags:/etc/osquery.flags
      - ./staks/ssl/certs/certificate.crt:/ssl/certificate.crt:ro
      - /data
    depends_on:
      - proxy
    environment:
      - ENROLL_SECRET=${ENROLL_SECRET:?ENROLL_SECRET is required}
