# -*- coding: utf-8 -*-
import six

CMDB_RU_TRANSLATIONS = {
    # Object Types
    'system_info': 'Сведения о системе',
    'os_version': 'Операционная система',
    'local_users': 'Учетные записи',
    'software': 'Установленное ПО',
    'programs': 'Установленное ПО',
    'network': 'Сетевые интерфейсы',
    'usb_devices': 'USB устройства',
    'logical_drives': 'Дисковое пространство',
    'uptime': 'Время работы',
    'patches': 'Установленные обновления',
    'startup_items': 'Автозагрузка',
    'services': 'Службы Windows',
    'scheduled_tasks': 'Запланированные задачи',
    'shared_folders': 'Общие ресурсы',
    'drivers': 'Установленные драйверы',
    'bitlocker': 'Шифрование BitLocker',
    'storage_mounts': 'Точки монтирования',

    # Actions
    'added': 'Добавлено',
    'removed': 'Удалено',

    # Columns / Attributes
    'blocks': 'Размер (Блоков)',
    'blocks_free': 'Свободно (Блоков)',
    'blocks_size': 'Размер блока (Байт)',
    'device': 'Устройство',
    'hostname': 'Имя хоста',
    'cpu_brand': 'Процессор',
    'cpu_physical_cores': 'Физические ядра',
    'cpu_logical_cores': 'Логические ядра',
    'physical_memory': 'Оперативная память',
    'hardware_vendor': 'Производитель',
    'hardware_model': 'Модель устройства',
    'hardware_serial': 'Серийный номер',
    'name': 'Название',
    'make': 'Производитель',
    'cpu': 'Процессор',
    'cpu cores': 'Количество ядер',
    'memory': 'Оперативная память',
    'version': 'Версия',
    'publisher': 'Издатель',
    'install_date': 'Дата установки',
    'vendor': 'Производитель',
    'model': 'Модель',
    'serial': 'Серийный номер',
    'usb_port': 'Порт USB',
    'interface': 'Интерфейс',
    'address': 'IP-адрес',
    'mask': 'Маска подсети',
    'mac': 'MAC-адрес',
    'username': 'Имя пользователя',
    'description': 'Описание',
    'directory': 'Домашний каталог',
    'uuid': 'Идентификатор (UUID)',
    'type': 'Тип',
    'hotfix_id': 'Идентификатор KB',
    'installed_by': 'Установлено пользователем',
    'installed_on': 'Установлено дата',
    'path': 'Путь',
    'status': 'Статус',
    'device_id': 'Идентификатор устройства',
    'free_space': 'Свободно (Байт)',
    'size': 'Общий размер (Байт)',
    'file_system': 'Файловая система',
    'days': 'Дней',
    'hours': 'Часов',
    'minutes': 'Минут',
    'total_seconds': 'Всего секунд',
    'display_name': 'Отображаемое имя',
    'start_type': 'Тип запуска',
    'user_account': 'Учетная запись службы',
    'action': 'Действие',
    'enabled': 'Включено',
    'last_run_time': 'Последний запуск',
    'next_run_time': 'Следующий запуск',
    'inf': 'INF-файл',
    'provider': 'Поставщик',
    'date': 'Дата',
    'signed': 'Подпись',
    'drive_letter': 'Буква диска',
    'persistent_volume_id': 'Идентификатор тома',
    'protection_status': 'Статус защиты',
    'encryption_method': 'Метод шифрования',
}

def ru_translate(value):
    if not value:
        return value
    if isinstance(value, six.string_types):
        return CMDB_RU_TRANSLATIONS.get(value, value.replace('_', ' ').capitalize())
    return value
